server:
  path: ~/workspace/voxtale/storage/text/temp.txt
  encoding: utf-8
tts:
  model_folder: ./models/matcha-icefall-zh-baker
  model: model-steps-3.onnx
  vocoder: hifigan_v2.onnx
  lexicon: lexicon.txt
  dict_dir: dict
  tokens: tokens.txt
  rule_fsts: phone.fst, number.fst, date.fst
  sid: 0
  speed: 1.3
